const apiContainer = {
  department: "/department",
  permission: "/permission",
  setting: "/setting",
  designation: "/designation",
  bankAccount: "/bank-account",
  employeeLogin: "/organization-login",
  role: "/role",
  uploadImages: "/upload-proof",
  petrolAllowance: "/petrol-allowance",
  activity: "/activity",
  claimType: "/claim-type",
  claim: "/claim",
  branch: "/branch",
  proofType: "/proof-type",
  transferStaff: "/transfer-staff",
  advancePaymentHistory: "/advance-payment-history",
  settingWorkingDay: "/setting-working-day",
  settingLeaveDeduction: "/setting-leave-deduction",
  settingBenefit: "/setting-benefit",
  attendanceIncharge: "/attendance-incharge",
  staffAdvance: "/staff-advance",
  deputation: "/deputation",
  holiday: "/holiday",
  staff: "/staff",
  staffDetails: "/staff-details",
  staffProof: "/staff-proof",
  staffLanguage: "/staff-known-language",
  staffQualification: "/staff-qualification",
  staffRelation: "/staff-relation",
  staffWorkExperience: "/work-experience",
  staffLeave: "/staff-leave",
  staffAttendance: '/staff-attendance',
  staffSalary: "/staff-salary-history",
  staffOnDuty: "/staff-onduty",
  staffRights: "/staff-rights",
  trainingType: "/training-type",
  staffTraining: "/staff-training",
  //report
  staffAttendanceReport: "/staff-attendance-report",
  petrolAllowanceReport: "/petrol-allowance-report",
  rolePermission: "/role-permission",
  salaryIncreamentHistory: "/salary-increament-history",
};

export default apiContainer;
